### PR TITLE
TW-3568: add EventVisibilityResolver and change visibility rules

### LINKED ISSUE #2955: [BUG] Wrong message displayed after reaction removal
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When I remove a reaction the app displays "Quentin deleted a message". But no, it's not a message, it's only a reaction. I don't know if we want to display this event at all. 

https://github.com/user-attachments/assets/27191e94-b0cf-4699-a92b-f63d0bea8203

### Pre-Bug State

.

### To Reproduce

1. Add a reaction
2. Remove the reaction
3. See the evens displayed in the side bar

### Expected results

- I don't know if we want to display an event at all for this. But I'm sure it should not be "deleted a message" 

### Context

- web version 2.20.6

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Additional information

- Frequency
- Others

### PR DESCRIPTION
**Pull request by jbrnzl**
## Changes

- **EventTypeSets** (lib/domain/matrix_events/event_type_sets.dart): single table of Matrix event types with visibility group (alwaysVisible, unimportant, neverInTimeline, unknown) and derived sets messageContentTypes / userContentTypes / showInChatListTypes.
- **Added EventVisibilityResolver** (lib/domain/matrix_events/event_visibility_resolver.dart):
  - **isVisibleInTimeline**: chat timeline (relationship > type > AppConfig > content heuristics).
  - **isEligibleForChatListPreview**: chat-list preview (allowed types, redaction, edit chain via getEventById).
- **filtered_timeline_extension.dart**: isVisibleInGui delegates to the resolver
- **room_extension.dart**: lastEventAvailableInPreview simplified: walks recent DB events and keeps the newest that passes the resolver (removed legacy state-heavy branches and ad-hoc filters).
- **event_extension.dart**: removed obsolete preview helpers (shouldHideBannedEvent, shouldHideChangedAvatarEvent, shouldHideChangedDisplayNameEvent).
- **chat_list_item_subtitle.dart**: subtitle uses room.lastEvent only when its type is in showInChatListTypes, otherwise shows “This is a new chat”, single L10n.of(context)! in build.
- **Tests**: extended filtered_timeline_extension_test.dart, added event_visibility_resolver_preview_test.dart for chat-list preview rules.

## Impact description
**Users chat list**: Behavior changes for rooms with no eligible message: placeholder instead of relying on non-message events (e.g. certain state events) as preview text. Also many events (that are not UI messages) are removed from the preview.
**Users timeline**: User-visible behavior is now well aligned with AppConfig toggles and type groups as per internal choices, implementation is centralized for maintainability.
**Codebase**: Clearer separation of concerns, easier to extend (e.g. content rules list in the resolver), less duplicated filtering logic.

## Known limitations ❗

- In order to preserve performances, we do not load every chat timeline of each room. Some rooms without recent eligible preview events (=message) and no recent room creation event, can be marked as "Click to load the latest messages" as you can see in the web demos 2.

## Test recommendations
**Run**:
`flutter test test/utils/matrix_sdk_extensions/filtered_timeline_extension_test.dart test/domain/model/room/event_visibility_resolver_preview_test.dart`
**Manual**: room without an eligible last message → “This is a new chat” subtitle; room whose lastEvent is not a message type → that event should not drive the subtitle.
**Manual**: edited messages / redactions in the chain → chat-list subtitle matches preview rules.

## Demos
- Web

https://github.com/user-attachments/assets/9b7971ac-07e1-4529-85f1-2e03405efdd3

- Mobile

https://github.com/user-attachments/assets/e7c613a7-f373-4076-8bd9-7ead16d3700a

## Summary by CodeRabbit

* **New Features**
  * Added "This is a new chat" placeholder shown in chat lists when no messages are available.

* **Refactor**
  * Centralized event visibility and filtering to unify timeline, chat-preview and notification selection behavior.

* **UI Changes**
  * Call-related events now shown as generic/unknown messages; dedicated call-invite UI removed.
  * Subtitle styling class renamed and usages updated.

* **Tests**
  * Added tests for visibility rules and chat-list preview eligibility.

### CODE REVIEW

File: lib/domain/model/room/room_extension.dart [hunk 1]
```diff
@@ -158,130 +157,39 @@ extension RoomExtension on Room {
...
-              lastState.originServerTs.millisecondsSinceEpoch) {
-            lastEventAvailableInPreview = messageEvent;
-            break;
-          }
+          e,
+        )) {
+          best = _newestEvent(best, e);
         }
       }
+      return best;
```
[the remark this answers is not in the document]
Comment (jbrnzl) [reply lib/domain/model/room/room_extension.dart]: Agree. This was a problem I discussed with the product team. This was done intentionnaly to preserve performances and not load all the events for all the rooms a user have. With the new changes a room with a message far away in the room with a lot of events after can be flagged as "This is a new chat". This is a limitation from the new visibility behaviors asked. This case should be discussed with the team in a near future. Maybe we should have a display preview as "Click to synchronise the chat" but it would need some works to decide on how we can do it. I am open to suggestions.

File: lib/domain/matrix_events/event_visibility_resolver.dart [hunk 2]
```diff
@@ -0,0 +1,158 @@
...
+  static bool _isGroupNameChangeWhenCreate(Event event) {
+    return event.type == EventTypes.RoomName &&
+        event.content['name'] != null &&
+        event.prevContent?['name'] == null;
+  }
+
+  static bool _isGroupAvatarChangeWhenCreate(Event event) {
+    return event.type == EventTypes.RoomAvatar &&
+        event.content['url'] == null &&
+        event.prevContent?['url'] == null;
```
[the remark this answers is not in the document]
Comment (jbrnzl) [reply lib/domain/matrix_events/event_visibility_resolver.dart]: I agree, I did the changes and added tests.

File: lib/domain/matrix_events/event_visibility_resolver.dart [hunk 3]
```diff
@@ -0,0 +1,157 @@
...
+  static bool _passesRelationshipLayer(Event event) {
+    if ({
+      RelationshipTypes.edit,
+      RelationshipTypes.reaction,
+    }.contains(event.relationshipType)) {
+      return false;
+    }
+    if (event.type.startsWith('m.key.verification.')) return false;
+    return true;
+  }
```
Comment (nqhhdev) [inline lib/domain/matrix_events/event_visibility_resolver.dart:75]: _passesRelationshipLayer allocates a new Set literal on every call so consider extracting it as a static const.

```dart
static const _hiddenRelationships = {                                                                                                                                                                                                                                                                                                               
      RelationshipTypes.edit,                                                                                                                                                                                                                                                                                                                           
      RelationshipTypes.reaction,                                                                                                                                                                                                                                                                                                                       
    };    
                                                                                                                                                                                                                                                                                                                                                        
if (_hiddenRelationships.contains(event.relationshipType)) return false;     
```

File: lib/domain/matrix_events/event_visibility_resolver.dart [hunk 4]
```diff
@@ -0,0 +1,157 @@
...
+
+  static bool _isGroupNameChangeWhenCreate(Event event) {
+    return event.type == EventTypes.RoomName &&
+        event.content['name'] != null &&
+        event.prevContent?['name'] == null;
+  }
+
+  static bool _isGroupAvatarChangeWhenCreate(Event event) {
+    return event.type == EventTypes.RoomAvatar &&
+        event.prevContent?['url'] == null;
```
Comment (nqhhdev) [inline lib/domain/matrix_events/event_visibility_resolver.dart]: Logic changed from the original:

```dart
// old: hid the event only when both before AND after url were null                                                                                                                                                                                                                                                                                 
    content['url'] == null && prevContent?['url'] == null                                                                                                                                                                                                                                                                                               
                                                         
// new: hides any avatar event with no previous url — including first-time avatar set                                                                                                                                                                                                                                                               
prevContent?['url'] == null     
```
This now hides the first time a group sets an avatar, which is meaningful. Intentional?

File: lib/domain/matrix_events/event_visibility_resolver.dart [hunk 5]
```diff
@@ -0,0 +1,157 @@
...
+  }
+
+  static bool _isJoinedByYourself(Event event) {
+    return event.type == EventTypes.RoomMember &&
+        event.content['membership'] == 'join' &&
+        event.senderId == event.stateKey &&
+        event.stateKey == event.room.client.userID;
+  }
+
+  static bool _isInviteWhenCreate(Event event) {
```
Comment (nqhhdev) [inline lib/domain/matrix_events/event_visibility_resolver.dart]: Name says "WhenCreate" but hides all reason-less invites regardless of when they occur. Intentional, or should there be a creation-time guard?

File: lib/domain/matrix_events/event_visibility_resolver.dart [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+    return event.type == EventTypes.RoomMember &&
+        event.content['membership'] == 'invite' &&
+        event.content['reason'] == null;
+  }
+
+  static bool _isState(Event event) =>
+      !EventTypeRules.messageContentTypes.contains(event.type);
```
Comment (nqhhdev) [inline lib/domain/matrix_events/event_visibility_resolver.dart]: Duplicate of `event.isState` from filtered_timeline_extension.dart.
                                                                                                                                                                                    
Should replace `_isState(event)` with `event.isState`.

File: lib/domain/matrix_events/event_type_rules.dart
Comment (nqhhdev) [inline lib/domain/matrix_events/event_type_rules.dart:1]: Sticker and CallInvite lost isUserContent/isMessageContent flags. In the old EventTypeSets both were in messageContentTypes/userContentTypes.
=> Impact: sticker events in message.dart no longer match userContentTypes, fall through to the m.call.* guard, and render SizedBox.shrink() instead of the sticker widget. Same-sender grouping also breaks for stickers.

File: lib/domain/model/room/room_extension.dart [hunk 7]
```diff
@@ -158,130 +157,39 @@ extension RoomExtension on Room {
...
-        final lastState = _getLastestRoomState();
-
-        if (lastState == null) return null;
-
-        lastEventAvailableInPreview = lastState;
-        final messageEvents = await client.database.getEventList(
+      final dbEvents = await client.database.getEventList(this, limit: 30);
+      Event? best;
+      for (final e in dbEvents) {
+        if (await EventVisibilityResolver.isEligibleForChatListPreview(
```
Comment (nqhhdev) [inline lib/domain/model/room/room_extension.dart:197]: Old implementation: O(1) state-cache scan first, DB fallback only if needed.                                                                                                                                                                                                                                                                          
New implementation: always queries DB (limit: 30), state events excluded.   
                                                                                                                                                                                                                                                                                                                                                        Two concerns:                                                                                                                                                                                                                                                                                                                                         
  1. Freshly joined rooms with no local DB timeline will return null and show                                                                                                                                                                                                                                                                           
     "This is a new chat" even if state events (name/avatar change etc.) exist.                                                                                                                                                                                                                                                                         
  2. Unconditional DB query on every room list render — perf impact with many rooms.                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                        
If dropping state events from the subtitle is intentional, please document it.

File: lib/pages/chat_list/chat_list_item_subtitle.dart [hunk 8]
```diff
@@ -137,16 +145,31 @@ class ChatListItemSubtitle extends StatelessWidget with ChatListItemMixin {
...
     return TypingTimerWrapper(
       room: room,
-      l10n: L10n.of(context)!,
+      l10n: l10n,
       typingWidget: typingTextWidget(typingText, context),
-      notTypingWidget: isGroup
+      notTypingWidget: showPlaceholder
+          ? Text(
+              l10n.thisIsANewChat,
+              style: ChatLitSubSubtitleTextStyleView.textStyle.textStyle(
```
Comment (nqhhdev) [inline lib/pages/chat_list/chat_list_item_subtitle.dart]: typo, could you please check it

File: lib/pages/chat_list/chat_list_item_subtitle.dart [hunk 9]
```diff
@@ -21,14 +23,19 @@ class ChatListItemSubtitle extends StatelessWidget with ChatListItemMixin {
...
       room.isUnreadOrInvited,
       room.hasNewMessages,
       room.notificationCount > 0,
     );
-    final Event? lastEvent = this.lastEvent ?? room.lastEvent;
+    final Event? lastEvent =
+        this.lastEvent ??
+        (EventTypeRules.showInChatListTypes.contains(room.lastEvent?.type)
+            ? room.lastEvent
+            : null);
```
Comment (nqhhdev) [inline lib/pages/chat_list/chat_list_item_subtitle.dart]: Sync path (room.lastEvent + showInChatListTypes) and async path (isEligibleForChatListPreview) can resolve to different events — async also checks redaction and edit chains. Consider aligning or adding event.redacted check here. 

Should separate small func

File: lib/domain/matrix_events/event_visibility_resolver.dart (hunk 4 above)
Comment (jbrnzl) [reply lib/domain/matrix_events/event_visibility_resolver.dart]: Yes not intentional as a group can be created without an avatar and a user can set one longer after the creation. 👍🏻
I will revert back to the old implementation and maybe we can found later a better way to hide the noise of when a room is directly created with an avatar.

File: lib/domain/matrix_events/event_visibility_resolver.dart (hunk 6 above)
Comment (jbrnzl) [reply lib/domain/matrix_events/event_visibility_resolver.dart]: Yes, I will move it to EventTypeRules because I do not want to have an import loop where filtered_timeline_extension imports the EventVisibilityResolver, that imports filtered_timeline_extension.

File: lib/domain/matrix_events/event_type_rules.dart
Comment (jbrnzl) [reply lib/domain/matrix_events/event_type_rules.dart:1]: Ok, I will ask product team because from the internal documentation my work is based on, sticker event was part of "Events that the client has no renderer for ; that the application does not support yet". But I agree with you, even if we can not send, we can receive. 👍🏻
Edit: Decision is Stickers are kept shown in the timeline, calls events turns unknown: "Unknown event type: m.call.x" instead of the bubble if user preferences match.

File: lib/domain/model/room/room_extension.dart (hunk 7 above)
Comment (jbrnzl) [reply lib/domain/model/room/room_extension.dart:197]: @nqhhdev Yes forgot that check. For the state events from the subtitle PR description says "Also many events (that are not UI messages) are removed from the preview." so yes it was intentional

File: lib/domain/matrix_events/event_visibility_resolver.dart (hunk 5 above)
Comment (jbrnzl) [reply lib/domain/matrix_events/event_visibility_resolver.dart]: Renamed

**Comment by nqhhdev** [comment]
Hi @jbrnzl should fix up all comments from Rabbitai

**Comment by nqhhdev** [comment]
MO, after addressing the review comments, a newer demo should be added to reflect the updated logic, as this may help uncover any hidden regression issues and keep things clear.

cc: @jbrnzl what do you think?

File: lib/domain/matrix_events/event_visibility_resolver.dart [hunk 10]
```diff
@@ -0,0 +1,169 @@
...
+    return event.stateKey != null &&
+        event.prevContent?['membership'] == 'join' &&
+        event.prevContent?['avatar_url'] != event.content['avatar_url'];
+  }
+
+  static bool _isGroupNameChangeWhenCreate(Event event) {
+    return event.type == EventTypes.RoomName &&
+        event.content['name'] != null &&
+        event.prevContent?['name'] == null;
+  }
```
[the remark this answers is not in the document]
Comment (jbrnzl) [reply lib/domain/matrix_events/event_visibility_resolver.dart]: addressed

File: lib/domain/matrix_events/event_visibility_resolver.dart [hunk 11]
```diff
@@ -0,0 +1,169 @@
...
+    // Walk the edit chain; discard if any ancestor is redacted.
+    var id = event.relationshipEventId;
+    while (id != null) {
+      final target = await room.getEventById(id);
+      if (target == null) break;
+      if (target.redacted) return false;
+      id = target.relationshipType == RelationshipTypes.edit
+          ? target.relationshipEventId
+          : null;
+    }
```
[the remark this answers is not in the document]
Comment (jbrnzl) [reply lib/domain/matrix_events/event_visibility_resolver.dart:58]: addressed

File: lib/domain/model/room/room_extension.dart (hunk 1 above)
[the remark this answers is not in the document]
Comment (jbrnzl) [reply lib/domain/model/room/room_extension.dart]: We now search for m.room.create to mark a room as a “New chat.” For rooms without eligible events among those fetched and without an m.room.create, they are marked as “Click to load the latest messages,” as described in the Known limitations ❗ category of this PR’s description. This is the best compromise for now.

**Comment by jbrnzl** [comment]
> MO, after addressing the review comments, a newer demo should be added to reflect the updated logic, as this may help uncover any hidden regression issues and keep things clear.
> 
> cc: @jbrnzl what do you think?

updated ✅ please check them carefully 🙏🏻

**Comment by jbrnzl** [comment]
Hi @nqhhdev @9clg6 any other concerns, suggestions ? Please do not hesitate

**Comment by nqhhdev** [comment]
Hi @jbrnzl I'm testing and reviewing

**Comment by jbrnzl** [comment]
Hi @tprudentova can you please read the "Known limitations" part of the PR description with the demos and confirm that this is acceptable at least for now 🙏🏻

File: lib/domain/matrix_events/event_visibility_resolver.dart [hunk 12]
```diff
@@ -0,0 +1,176 @@
...
+  }
+
+  static bool _isSomeoneChangeDisplayName(Event event) {
+    return event.type == EventTypes.RoomMember &&
+        event.stateKey != null &&
+        event.content['membership'] == 'join' &&
+        event.prevContent?['membership'] == 'join' &&
+        event.prevContent?['displayname'] != null &&
+        event.prevContent!['displayname'] != event.content['displayname'];
+  }
```
Comment (nqhhdev) [inline lib/domain/matrix_events/event_visibility_resolver.dart:142]: Is this intentional for all rooms? Virtually no real invite has a `reason`, so this hides every invite everywhere — not just creation noise. If yes, please add a comment here. If no, gate on `prevContent == null`.

File: lib/pages/chat_list/chat_list_item_subtitle.dart [hunk 13]
```diff
@@ -137,16 +158,33 @@ class ChatListItemSubtitle extends StatelessWidget with ChatListItemMixin {
...
+
     return TypingTimerWrapper(
       room: room,
-      l10n: L10n.of(context)!,
+      l10n: l10n,
       typingWidget: typingTextWidget(typingText, context),
-      notTypingWidget: isGroup
+      notTypingWidget: showPlaceholder
+          ? Text(
+              previewResult is RoomPreviewUnavailable
```
Comment (nqhhdev) [inline lib/pages/chat_list/chat_list_item_subtitle.dart]: How about if `previewResult` is null? may be loading status

Comment (jbrnzl) [reply lib/pages/chat_list/chat_list_item_subtitle.dart]: Yes you are right, added :)

File: lib/domain/matrix_events/event_visibility_resolver.dart (hunk 12 above)
Comment (jbrnzl) [reply lib/domain/matrix_events/event_visibility_resolver.dart:142]: added prevContent == null

**Comment by tprudentova** [comment]
@jbrnzl two things: 
1. Can we pwease write "This is a new chat" in grey and in italic? Grey as in the same colour as for any other message in chat list. After that I will show this option to Diana for one last verification :) 
2. Same for the fonts for chats for which the last message isn't loaded, but also will the user actually see the latest message in the chat list after they open the chat? 

If you can make these font updates and add the new demos I'll be very grateful!

**Comment by jbrnzl** [comment]
> @jbrnzl two things:
> 
> 1. Can we pwease write "This is a new chat" in grey and in italic? Grey as in the same colour as for any other message in chat list. After that I will show this option to Diana for one last verification :)
> 2. Same for the fonts for chats for which the last message isn't loaded, but also will the user actually see the latest message in the chat list after they open the chat?
> 
> If you can make these font updates and add the new demos I'll be very grateful!

Thank you
1. Done, I updated the demos let me know if it's better
2. As soon as we encounter an eligible event in the timeline that can be shown in the chat list then yes (so sometimes you need to scroll up a little or load more messages). This is the counter part of not having the last event as a fallback (before, every events were eligible for chat list preview so we had at least one to show, now we need to find an eligible one, but if we load all the messages until one is encountered it can be overkill. Please let me know, and let's discuss it with the team if it is not acceptable for now so we can get feedbacks or suggestions on how to do better :)

**Comment by tprudentova** [comment]
> 2. As soon as we encounter an eligible event in the timeline that can be shown in the chat list then yes 

Does a message event fall into this category btw? 🤔

**Comment by jbrnzl** [comment]
> > 2. As soon as we encounter an eligible event in the timeline that can be shown in the chat list then yes
> 
> Does a message event fall into this category btw? 🤔

Yes messages are eligible events for the chat list preview 👍🏻

**Review by 9clg6 — APPROVED** [review]

**Comment by nqhhdev** [comment]
Hi @jbrnzl, please avoid using force push, as it prevents reviewers from comparing changes with previous commits after updates.

**Comment by jbrnzl** [comment]
> Hi @jbrnzl, please avoid using force push, as it prevents reviewers from comparing changes with previous commits after updates.

Hi @nqhhdev, you are right I will not squash-force push but keep the commits separated while it is in review in the future 🙏🏻
Thank you for your time

**Review by nqhhdev — APPROVED** [review]
