### PR TITLE
fix: add system pop in router

### LINKED ISSUE #184: `Back` in create dialog move the user out of the app

### PR DESCRIPTION
**Pull request by imGok**
- System back button has now the same behavior as in-app back button

backback

This Closes #184

### CODE REVIEW

**Comment by hoangdat** [comment]
@sherlockvn please carefully in reviewing, because of your handler :)))

**Comment by sherlockvn** [comment]
> * System back button has now the same behavior as in-app back button
> 
> backback
> 
> This Closes #184

In ContactsTab, or story tab, it will be back to close app @imGok Please check this case

**Comment by imGok** [comment]
> 
```
1. Chat List
2. New Chat
3. Back (system)
4. Back (system)
```
scenario1

```
1. Chat List
2. New Chat
3. Back (system)
4. Contact tab
5. Back (system)
6. Back (system)
```
scenario2

File: lib/config/routes.dart [hunk 1]
```diff
@@ -49,118 +49,134 @@ class AppRoutes {
...
-                widget: const Archive(),
-                buildTransition: rightToLeftTransition,
+        VRouter(
+          routes: [
+            VPopHandler(
+                onSystemPop: (vRedirector) async {
+                  if (vRedirector.previousVRouterData?.url != '/rooms') {
+                    vRedirector.to('/rooms');
+                  }
+                },
```
Comment (imGok) [inline lib/config/routes.dart:59]: @hoangdat this is the change

**Review by sherlockvn — APPROVED** [review]

**Comment by hoangdat** [comment]
please rebase it
