### PR TITLE
fix: reduce width of bubble messages

### LINKED ISSUE #411: Bubble width too large in direct chat
### Desc:

- In direct chat
- Message bubble expand too much in width

Image

### DoD:
- [ ] need to have margin left for own message 
- [ ] need to have margin right for received message

### PR DESCRIPTION
**Pull request by imGok**
Design : 
web version (620px)
image
mobile (272px)
image

Direct message : 
image
image

Group : 
image
image

Web :
image

This Closes #411

### CODE REVIEW

**Review by sherlockvn — APPROVED** [review]

File: lib/config/themes.dart [hunk 1]
```diff
@@ -8,6 +8,7 @@ import 'app_config.dart';
 
 abstract class FluffyThemes {
   static const double columnWidth = 360.0;
+  static const double bubbleMessageMaxWidth = 272.0;
```
Comment (hoangdat) [inline lib/config/themes.dart:11]: no, I dont think it is a good solution, how about in web? bigger screen?

File: lib/pages/chat/events/message.dart [hunk 2]
```diff
@@ -180,9 +180,8 @@ class Message extends StatelessWidget {
                                                       AppConfig
                                                           .bubbleSizeFactor,
                                             ),
-                                      constraints: const BoxConstraints(
-                                        maxWidth:
-                                            FluffyThemes.columnWidth * 1.5,
+                                      constraints: BoxConstraints(
+                                        maxWidth: MediaQuery.of(context).size.width * 0.8,
```
Comment (nqhhdev) [inline lib/pages/chat/events/message.dart:184]: IMO: Should use `Expanded(flex: ...)`, it good for this case

Comment (imGok) [reply lib/pages/chat/events/message.dart]: you are right it's more reliable

File: lib/pages/chat/events/message/message_style.dart [hunk 3]
```diff
@@ -33,7 +33,10 @@ class MessageStyle {
         : const Color.fromARGB(239, 36, 36, 36);
   }
 
-  static int get messageFlexMobile => 7;
+  static int messageFlexMobile(bool othersMessageNotInGroupChat) {
+    return othersMessageNotInGroupChat ? 3 : 5;
```
Comment (nqhhdev) [inline lib/pages/chat/events/message/message_style.dart:37]: IMO: With your rate quite small for this monitor

Comment (sherlockvn) [reply lib/pages/chat/events/message/message_style.dart:37]: What about in landscape mode in mobile

Comment (imGok) [reply lib/pages/chat/events/message/message_style.dart:37]: IMO it's fine like this doesn't take much space in landscape mode
I did 3 for others message in group chat because there is avatar 
image
demo_msg_width222

Comment (nqhhdev) [reply lib/pages/chat/events/message/message_style.dart:37]: IMO: It's okay

Comment (hoangdat) [reply lib/pages/chat/events/message/message_style.dart:37]: hope it bigger in portrait screen. ( I talked in details with Julian in meeting)

Comment (imGok) [reply lib/pages/chat/events/message/message_style.dart]: demodemo
this is 4 instead of 3 flex

**Review by drminh2807 — APPROVED** [review]

File: lib/pages/chat/events/message/message_style.dart (hunk 3 above)
Comment (hoangdat) [reply lib/pages/chat/events/message/message_style.dart]: IMO, it is still a lot of space in view. Try to keep the UI good but need to prioritize the main function of communication.
We need to align the left/right and also manage the maximum width. WDYT?

Comment (imGok) [reply lib/pages/chat/events/message/message_style.dart]: for me we should put a fixed margin and update  it if the device is mobile or web

Comment (imGok) [reply lib/pages/chat/events/message/message_style.dart]: image
image

**Review by sherlockvn — APPROVED** [review]

File: lib/pages/chat/events/message/message_style.dart (hunk 3 above)
Comment (hoangdat) [reply lib/pages/chat/events/message/message_style.dart]: how about demo in web or landscape?

Comment (imGok) [reply lib/pages/chat/events/message/message_style.dart]: web version doesn't use this style, it looks like before 
image

**Comment by imGok** [comment]
I removed flex property and put a fixed width that switch between web and mobile version according to figmas design, read description

**Comment by sherlockvn** [comment]
In the new design, 
In Mobile portrait mode, The maxWidth for a message in chat is 272, and if it has an avatar, the maxWidth of the message also is 272.

In the Web version or mobile landscape, the maxWidth for a message is 572
- Currently, you should focus on text messages, not images or videos.
- If you find a lot of mobile devices that have a width is less than or approximately 272, I think you should use ratio. Otherwise, I think use number is fine.

**Comment by imGok** [comment]
@sherlockvn based on android devices, small phones are old ones. So IMO fixed pixels width shouldn't be a problem
image
here is landscape view 
image

**Comment by imGok** [comment]
web width remains 620 on figma for me 
image
I put 272 for mobile

**Review by sherlockvn — APPROVED** [review]

File: lib/pages/chat/events/message/message_style.dart [hunk 4]
```diff
@@ -47,4 +48,17 @@ class MessageStyle {
   static double get forwardContainerSize => 40.0;
   static Color? forwardColorBackground(context) =>
       Theme.of(context).colorScheme.surfaceTint.withOpacity(0.08);
+
+  static const double messageBubbleLargeMaxWidth = 620.0;
+  static const double messageBubbleWatchMaxWidth = 240.0;
+  static const double messageBubbleMobileRatioMaxWidth = 0.80;
+  static double messageBubbleWidth(BuildContext context) {
+    return context.responsiveValue<double>(
```
Comment (hoangdat) [inline lib/pages/chat/events/message/message_style.dart:56]: cool function, but the breakpoint is not exactly what we define

**Review by hoangdat — APPROVED** [review]
