### PR TITLE
fix: add font size to M3 styles

### LINKED ISSUE #239: [UI] Sender name label in group chat is having wrong text font
OS:  Android
Device: Mobile
TMail version:  2.1.3

### *Reproduce Step:
1, User open a group conversation
2, Focus on name label of sender in group chat

### **Actual:** 
- The font is Inter

Image

### **Expected:** 
- The font should be Roboto

Image

### PR DESCRIPTION
**Pull request by imGok**
waiting for designer reply

image

This Closes #239

### CODE REVIEW

File: lib/pages/chat/events/message.dart [hunk 1]
```diff
@@ -188,6 +188,7 @@ class Message extends StatelessWidget {
                                                           .labelMedium
                                                           ?.copyWith(
                                                             fontWeight: FontWeight.w500,
+                                                            fontFamily: 'Roboto',
```
Comment (nqhhdev) [inline lib/pages/chat/events/message.dart:191]: IMO: pls make it flexible, if it is not flexible I think it will be very hard to manage

File: lib/config/themes.dart [hunk 2]
```diff
@@ -19,25 +19,61 @@ abstract class FluffyThemes {
...
-    displaySmall: fallbackTextStyle,
-    headlineMedium: fallbackTextStyle,
-    headlineSmall: fallbackTextStyle,
-    titleLarge: fallbackTextStyle,
-    titleMedium: fallbackTextStyle,
-    titleSmall: fallbackTextStyle,
+  static const fallBackTextStyleRoboto = TextStyle(
+    fontFamily: 'Roboto',
+    fontFamilyFallback: ['Roboto'],
+  );
```
Comment (hoangdat) [inline lib/config/themes.dart:30]: no, please remove all the thing related to `Roboto`

**Review by hoangdat — APPROVED** [review]

File: lib/pages/chat/events/message_content.dart [hunk 3]
```diff
@@ -203,7 +203,7 @@ class MessageContent extends StatelessWidget {
                 padding: const EdgeInsets.only(left: 8.0, right: 8.0),
                 child: HtmlMessage(
                   html: html,
-                  defaultTextStyle: TextStyle(
+                  defaultTextStyle: Theme.of(context).textTheme.bodyLarge?.copyWith(
```
Comment (hoangdat) [inline lib/pages/chat/events/message_content.dart:206]: this ticket for `Sender name`, but only see the change for the `content`. It is hard for reviewing. Please keep your logic focus to the scope of ticket

**Review by sherlockvn — APPROVED** [review]

**Review by nqhhdev — APPROVED** [review]
